kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.08933618152582981
    roll: -0
    pitch: 0
    yaw: 3.97283969315073e-05
  upper_arm:
    x: 0.0003394920063376269
    y: 0
    z: 0
    roll: 1.570913778408139
    pitch: 0
    yaw: 4.743082691347971e-05
  forearm:
    x: -0.4253113388931802
    y: 0
    z: 0
    roll: 3.141434123809435
    pitch: 3.141191830272886
    yaw: -3.141546587775657
  wrist_1:
    x: -0.3928758821855175
    y: -0.0002591578237811456
    z: 0.1096465775454547
    roll: 0.00236356981668423
    pitch: -0.002940366198870254
    yaw: -4.343307252557929e-05
  wrist_2:
    x: -4.866964894212868e-05
    y: -0.09491254520006147
    z: 0.0001046561446438712
    roll: 1.569693668531885
    pitch: 0
    yaw: -3.84894355660732e-05
  wrist_3:
    x: 5.233347846931688e-05
    y: 0.08262007961154672
    z: 5.110935618237711e-05
    roll: 1.571414933674765
    pitch: 3.141592653589793
    yaw: 3.141547420379037
  hash: calib_2648660833544506115