standalone_tags:
    [
    {id: 0, size: 0.161},
    {id: 42, size: 0.1535}
    ]
tag_bundles:
    [
        {
            name: 'ur5_mount_bundle',
                      layout:
                          [
                          {id: 128, size: 0.08, x: 0.0, y: -0.2, z:  0.3, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
                          {id: 154, size: 0.08, x: 0.0, y: 0.2, z:  0.3,  qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
                          {id: 162, size: 0.08, x: 0.0, y: -0.2, z: -0.3, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
                          {id: 164, size: 0.08, x: 0.0, y: 0.2, z: -0.3,  qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5}
                          ]
        }
    ]
