arm:
  #kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin

  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 1

  # tracik
  solve_type: Distance

  # ur kinematics
  arm_prefix: ur5_

